//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudCoin_SafeScan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudCoin_SafeScan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.Add() decrypting exception: .
        /// </summary>
        public static string AddDecryptingException {
            get {
                return ResourceManager.GetString("AddDecryptingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.Add() IO write exception:.
        /// </summary>
        public static string AddIOException {
            get {
                return ResourceManager.GetString("AddIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.Add() JSON serialize exception: .
        /// </summary>
        public static string AddJsonException {
            get {
                return ResourceManager.GetString("AddJsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated.
        /// </summary>
        public static string Authenticated {
            get {
                return ResourceManager.GetString("Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC in your Safe.
        /// </summary>
        public static string CCinSafe {
            get {
                return ResourceManager.GetString("CCinSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Ownership?.
        /// </summary>
        public static string ChangeOwnership {
            get {
                return ResourceManager.GetString("ChangeOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudCoin Scan&amp;Safe - CheckCoins.
        /// </summary>
        public static string CheckCoinsWindowTitle {
            get {
                return ResourceManager.GetString("CheckCoinsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The RAIDA does not respond.
        ///Check your internet connection
        ///Work with local Safe is still possible&quot;.
        /// </summary>
        public static string CheckInternet {
            get {
                return ResourceManager.GetString("CheckInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to change ownership and import money in Safe?
        ///Choosing &quot;No&quot; will simply scan coins without changing passwords..
        /// </summary>
        public static string CheckOrImport {
            get {
                return ResourceManager.GetString("CheckOrImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get cloudcoins (new worldwide currency) in form of files from anywhere - sites, emails, USB Sticks, Smartphones... This app just checks them for counterfeit, loads and keeps &apos;em in safe and makes stacks for payments or gifts..
        /// </summary>
        public static string CloudCoinDescription {
            get {
                return ResourceManager.GetString("CloudCoinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudCoin Scan&amp;amp;Safe.
        /// </summary>
        public static string CloudCoinTitle {
            get {
                return ResourceManager.GetString("CloudCoinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.CreateSafeFile() encryption exception: .
        /// </summary>
        public static string CreateEncryptionException {
            get {
                return ResourceManager.GetString("CreateEncryptionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.CreateSafeFile() JSON exception: .
        /// </summary>
        public static string CreateJsonException {
            get {
                return ResourceManager.GetString("CreateJsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.CreateSafeFile() IO write exception: .
        /// </summary>
        public static string CreateWriteException {
            get {
                return ResourceManager.GetString("CreateWriteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Fracked Again.
        /// </summary>
        public static string DetectFracked {
            get {
                return ResourceManager.GetString("DetectFracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. Hover for status..
        /// </summary>
        public static string DoneRAIDA {
            get {
                return ResourceManager.GetString("DoneRAIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echoing RAIDA nodes....
        /// </summary>
        public static string EchoRAIDA {
            get {
                return ResourceManager.GetString("EchoRAIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Safe Password.
        /// </summary>
        public static string EnterSafePassword {
            get {
                return ResourceManager.GetString("EnterSafePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sum you want to withdraw. The app will export coins with nearest possible value..
        /// </summary>
        public static string EnterSumWithdraw {
            get {
                return ResourceManager.GetString("EnterSumWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to check Windows version The program was closed..
        /// </summary>
        public static string ErrWinVer {
            get {
                return ResourceManager.GetString("ErrWinVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App will export stack of coins .
        /// </summary>
        public static string ExportStackCoins {
            get {
                return ResourceManager.GetString("ExportStackCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fives.
        /// </summary>
        public static string Fives {
            get {
                return ResourceManager.GetString("Fives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Fracked.
        /// </summary>
        public static string FixFracked {
            get {
                return ResourceManager.GetString("FixFracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing.
        /// </summary>
        public static string Fixing {
            get {
                return ResourceManager.GetString("Fixing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixProcessWindow.
        /// </summary>
        public static string FixProcessWindowTitle {
            get {
                return ResourceManager.GetString("FixProcessWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: .
        /// </summary>
        public static string FnF {
            get {
                return ResourceManager.GetString("FnF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractioned.
        /// </summary>
        public static string Fractioned {
            get {
                return ResourceManager.GetString("Fractioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full coins.
        /// </summary>
        public static string FullCoins {
            get {
                return ResourceManager.GetString("FullCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half coins (safe).
        /// </summary>
        public static string HalfCoins {
            get {
                return ResourceManager.GetString("HalfCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundreds.
        /// </summary>
        public static string Hundreds {
            get {
                return ResourceManager.GetString("Hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG.
        /// </summary>
        public static string JPEG {
            get {
                return ResourceManager.GetString("JPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures with coins saved in Export dir
        ///.
        /// </summary>
        public static string JpegExported {
            get {
                return ResourceManager.GetString("JpegExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KQuarters.
        /// </summary>
        public static string Kiloquarters {
            get {
                return ResourceManager.GetString("Kiloquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be less than 5 characters.
        /// </summary>
        public static string LessThen5Password {
            get {
                return ResourceManager.GetString("LessThen5Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Windows version is too low. This app works on Windows7 and higher.
        /// </summary>
        public static string LowWinVer {
            get {
                return ResourceManager.GetString("LowWinVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudCoin Scan&amp;Safe.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearest possible value..
        /// </summary>
        public static string NearestValue {
            get {
                return ResourceManager.GetString("NearestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node hasn&apos;t respond yet....
        /// </summary>
        public static string NodeNotRespond {
            get {
                return ResourceManager.GetString("NodeNotRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to export!.
        /// </summary>
        public static string NothingExported {
            get {
                return ResourceManager.GetString("NothingExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string NotMatchPassword {
            get {
                return ResourceManager.GetString("NotMatchPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ones.
        /// </summary>
        public static string Ones {
            get {
                return ResourceManager.GetString("Ones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarters.
        /// </summary>
        public static string Quarters {
            get {
                return ResourceManager.GetString("Quarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.ReadSafeFile() decrypting exception: .
        /// </summary>
        public static string ReadDecryptingException {
            get {
                return ResourceManager.GetString("ReadDecryptingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.ReadSafeFile() IO read exception: .
        /// </summary>
        public static string ReadIOException {
            get {
                return ResourceManager.GetString("ReadIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.ReadSafeFile() JSON deserialize exception: .
        /// </summary>
        public static string ReadJsonException {
            get {
                return ResourceManager.GetString("ReadJsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe.
        /// </summary>
        public static string Safe {
            get {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe Content.
        /// </summary>
        public static string SafeContentWindowTitle {
            get {
                return ResourceManager.GetString("SafeContentWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudStackOut.SaveInFile IO exception: .
        /// </summary>
        public static string SaveIOException {
            get {
                return ResourceManager.GetString("SaveIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudStackOut.SaveInFile Serialize exception: .
        /// </summary>
        public static string SaveSerializeException {
            get {
                return ResourceManager.GetString("SaveSerializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems that you did not set up your password yet. Please, enter one and then verify. Write down 
        ///your password in safe place. If you forget 
        ///one it will be impossible to restore and you&apos;ll
        ///loose all of your cloudcoins, unless you 
        ///haven&apos;t written down their serial numbers..
        /// </summary>
        public static string SeemsNotSetPassword {
            get {
                return ResourceManager.GetString("SeemsNotSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectOutStackWindow.
        /// </summary>
        public static string SelectOutStackWindowTitle {
            get {
                return ResourceManager.GetString("SelectOutStackWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select stack which contains nearest requested amount..
        /// </summary>
        public static string SelectStackWithAmount {
            get {
                return ResourceManager.GetString("SelectStackWithAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password for your CloudCoin Safe.
        /// </summary>
        public static string SetPasswordWindowTitle {
            get {
                return ResourceManager.GetString("SetPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter short note (e.g. For Alex).
        /// </summary>
        public static string ShortNote {
            get {
                return ResourceManager.GetString("ShortNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON stack of coins saved in Export dir\n.
        /// </summary>
        public static string StackExported {
            get {
                return ResourceManager.GetString("StackExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum:.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short. Use more than 5 characters.
        /// </summary>
        public static string TooShortPassword {
            get {
                return ResourceManager.GetString("TooShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250s.
        /// </summary>
        public static string TwoHundredsFifty {
            get {
                return ResourceManager.GetString("TwoHundredsFifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception catched:.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        public static string With {
            get {
                return ResourceManager.GetString("With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sum to Give Away.
        /// </summary>
        public static string WithdrawDialogTitle {
            get {
                return ResourceManager.GetString("WithdrawDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password from safe.
        ///Try again..
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CC in Safe.
        /// </summary>
        public static string ССinSafe {
            get {
                return ResourceManager.GetString("ССinSafe", resourceCulture);
            }
        }
    }
}
