//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudCoin_SafeScan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudCoin_SafeScan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Ownership?.
        /// </summary>
        public static string ChangeOwnership {
            get {
                return ResourceManager.GetString("ChangeOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to change ownership and import money in Safe?\nChoosing \&quot;No\&quot; will simply scan coins without changing passwords..
        /// </summary>
        public static string CheckOrImport {
            get {
                return ResourceManager.GetString("CheckOrImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to check Windows version The program was closed..
        /// </summary>
        public static string ErrWinVer {
            get {
                return ResourceManager.GetString("ErrWinVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: .
        /// </summary>
        public static string FnF {
            get {
                return ResourceManager.GetString("FnF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures with coins saved in Export dir\n.
        /// </summary>
        public static string JpegExported {
            get {
                return ResourceManager.GetString("JpegExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Windows version is too low. This app works on Windows7 and higher.
        /// </summary>
        public static string LowWinVer {
            get {
                return ResourceManager.GetString("LowWinVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to export!.
        /// </summary>
        public static string NothingExported {
            get {
                return ResourceManager.GetString("NothingExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON stack of coins saved in Export dir\n.
        /// </summary>
        public static string StackExported {
            get {
                return ResourceManager.GetString("StackExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception catched:.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
